pool: server
steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'databricks'
    method: 'GET'
    headers: |
      {
      }
    urlSuffix: 'api/2.1/jobs/runs/get?run_id=1023731582326422'
    waitForCompletion: 'false'
