pool: server
steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'databricks'
    method: 'GET'
    headers: |
      {
      }
    urlSuffix: 'api/2.0/clusters/list'
    waitForCompletion: 'true'
